### ISSUE TITLE
Control-Space isn't code completing as expected

### ISSUE THREAD

**Issue by sethladd** [radicaled/dart-tools#25]
Hi,

I tried to code complete, and it didn't work as expected. I'm on a Mac with Dart 1.10

1) Trying control-shift-space, and nothing happens.

2) Trying control-space, and I get this:

![screen shot 2015-05-15 at 9 57 19 am](https://cloud.githubusercontent.com/assets/5479/7657709/f021bdf2-fae8-11e4-996d-ce6d58780b90.png)

**Comment by sethladd** [comment]
If there's a log or something I can paste in, please let me know. Thanks!

**Comment by radicaled** [comment]
You'll need autocomplete-plus installed: atom.io/packages/autocomplete-plus

You **may** also need to disable the built-in `autocomplete` package, because it looks like the very latest version of `autocomplete-plus` (released 12 hours ago?) is now fighting with `autocomplete` for who owns "ctrl+space" autocompletion. But Atom owns autocomplete-plus now, so maybe they're moving from `autocomplete` to `autocomplete-plus`? Who knows. It's a mess they're probably trying to fix for 1.0 next month.

Alternatively, if you know how, you can redefine the autocomplete-plus autocompletion to anything you want. Here's the current autocomplete-plus defaults, for example:

```
'atom-text-editor':
  'ctrl-space': 'autocomplete-plus:activate'
```

#### Failing that

If you summon the Command Palette (CTRL+SHIFT+P or CMD+SHIFT+P), type in "Dev" and look for "Toggle Dev Tools", you'll get the typical Chrome / Chromium dev tools. There will probably be an error in the console.

**Comment by radicaled** [comment]
Also, you should see a notification in the upper right hand corner that says "[dart-tools] analysis server is now running" after a few seconds.

If you don't, then it definitely crashed.

**Comment by radicaled** [comment]
@sethladd update to 0.9.7, restart your atom instances, and let me know if this isn't working.

**Comment by sethladd** [comment]
I just did a fresh install of Atom.
I *only* installed the dart-tools plugin.
I configured my SDK.

Ta da, it works! :)
