### ISSUE TITLE
Dart formatting should respect Atom's setting for preferred line length

### ISSUE THREAD

**Issue by danschultz** [radicaled/dart-tools#44]
The `dartfmt` tool has an option for line length. When setting the preferred line length in Atom, it should be passed to `dartfmt` when saving a Dart file.

**Comment by radicaled** [comment]
Seems it does!

But on second glance of my own code that I wrote like a week ago and completely forgot about, we're using the `analysis_server` so that formatting can be applied through the editor so that the user's caret position doesn't go nuts.

IIRC, when I was using `dartfmt` externally it always truncated the file to 0 bytes before injecting the formatted contents, which meant that if you tried to CTRL-Z the formatting for whatever reason, you ended up with a scary blank file.

**Comment by radicaled** [comment]
Enhancement request for analysis server to support configurable line lengths: https://code.google.com/p/dart/issues/detail?id=23519&thanks=23519&ts=1432414239

I'd like to keep using as much of the analysis server as possible, but if this enhancement gets shot down I'll look into what it takes to use `dartfmt` without nuking the text buffer and losing the user's caret position.

**Comment by radicaled** [comment]
This feature landed!

...

But I'm not sure how to detect if the currently running analysis_server supports it.

**Comment by devoncarew** [comment]
I think you'll be able to pass in the `lineLength` param - newer versions will respect the param, and older versions will (_should_) ignore it.

**Comment by radicaled** [comment]
Hm, you're right. I thought at one point the analysis_server complained if you sent it a parameter it didn't understand, but it seems to work alright...

**Comment by radicaled** [comment]
In but inactive until you upgrade to a version of Dart that has an analysis_server that supports this feature (or until analysis_server starts being distributed independently of the Dart SDK so we can use the latest and greatest).
